"""add_trend_alert_settings_table

Revision ID: 0427f58ba939
Revises: 8ae1731bf9f0
Create Date: 2026-03-19 16:08:44.290950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0427f58ba939'
down_revision: Union[str, None] = '8ae1731bf9f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trend_alert_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('min_viral_score', sa.Float(), nullable=False),
    sa.Column('min_growth_rate', sa.Float(), nullable=False),
    sa.Column('niche_ids', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('notify_new_trend', sa.Boolean(), nullable=False),
    sa.Column('notify_viral_trend', sa.Boolean(), nullable=False),
    sa.Column('notify_niche_spike', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', name='uq_trend_alert_settings_workspace')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trend_alert_settings')
    # ### end Alembic commands ###
