"""add workspace_invitations table and is_platform_owner field

Revision ID: 1df12fc898d5
Revises: c7de8c3861e3
Create Date: 2026-03-12 16:10:48.345081

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1df12fc898d5"
down_revision: str | None = "c7de8c3861e3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    invitationstatus = postgresql.ENUM(
        "PENDING", "ACCEPTED", "EXPIRED", "CANCELLED", name="invitationstatus", create_type=False
    )
    invitationstatus.create(op.get_bind(), checkfirst=True)

    op.create_table(
        "workspace_invitations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("workspace_id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            postgresql.ENUM(
                "OWNER", "ADMIN", "EDITOR", "VIEWER", "CONTRACTOR", name="workspacerole", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("invited_by_user_id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM("PENDING", "ACCEPTED", "EXPIRED", "CANCELLED", name="invitationstatus", create_type=False),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["invited_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_invitations_email_status", "workspace_invitations", ["email", "status"], unique=False)
    op.create_index("ix_invitations_token", "workspace_invitations", ["token"], unique=True)
    op.create_index(
        "uq_invitations_workspace_email_pending",
        "workspace_invitations",
        ["workspace_id", "email"],
        unique=True,
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.add_column("users", sa.Column("is_platform_owner", sa.Boolean(), server_default=sa.false(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_platform_owner")
    op.drop_index(
        "uq_invitations_workspace_email_pending",
        table_name="workspace_invitations",
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.drop_index("ix_invitations_token", table_name="workspace_invitations")
    op.drop_index("ix_invitations_email_status", table_name="workspace_invitations")
    op.drop_table("workspace_invitations")
    sa.Enum(name="invitationstatus").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
