"""add content_items table

Revision ID: 287530c10c6a
Revises: 0e8b8dcf8f30
Create Date: 2026-03-11 19:12:22.741292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '287530c10c6a'
down_revision: Union[str, None] = '0e8b8dcf8f30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('added_by_user_id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('source_type', sa.Enum('YOUTUBE_VIDEO', name='sourcetype'), nullable=False),
    sa.Column('video_id', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='contentstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('raw_file_path', sa.String(length=1024), nullable=True),
    sa.Column('audio_path', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['added_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_content_items_added_by', 'content_items', ['added_by_user_id'], unique=False)
    op.create_index('ix_content_items_workspace_id', 'content_items', ['workspace_id'], unique=False)
    op.create_index('ix_content_items_workspace_status', 'content_items', ['workspace_id', 'status'], unique=False)
    op.create_index('ix_content_items_workspace_video', 'content_items', ['workspace_id', 'video_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL AND video_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_content_items_workspace_video', table_name='content_items', postgresql_where=sa.text('deleted_at IS NULL AND video_id IS NOT NULL'))
    op.drop_index('ix_content_items_workspace_status', table_name='content_items')
    op.drop_index('ix_content_items_workspace_id', table_name='content_items')
    op.drop_index('ix_content_items_added_by', table_name='content_items')
    op.drop_table('content_items')
    # ### end Alembic commands ###
