"""add transcriptions table and downloading status

Revision ID: 5a92436f2681
Revises: 287530c10c6a
Create Date: 2026-03-12 08:46:57.116037

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5a92436f2681"
down_revision: str | None = "287530c10c6a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Add 'downloading' value to contentstatus enum (Alembic doesn't detect enum changes)
    op.execute("ALTER TYPE contentstatus ADD VALUE IF NOT EXISTS 'downloading'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transcriptions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("content_item_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "PROCESSING", "COMPLETED", "FAILED", name="transcriptionstatus"),
            nullable=False,
        ),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("language", sa.String(length=10), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("whisper_model", sa.String(length=20), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("celery_task_id", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_item_id"],
            ["content_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_transcriptions_status", "transcriptions", ["status"], unique=False)
    op.create_index("uq_transcriptions_content_item_id", "transcriptions", ["content_item_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_transcriptions_content_item_id", table_name="transcriptions")
    op.drop_index("ix_transcriptions_status", table_name="transcriptions")
    op.drop_table("transcriptions")
    # ### end Alembic commands ###
