"""add content_intelligence table

Revision ID: 64a95c43ed7e
Revises: b9178608000d
Create Date: 2026-03-18 20:07:53.429277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '64a95c43ed7e'
down_revision: Union[str, None] = 'b9178608000d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_intelligence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('content_item_id', sa.Integer(), nullable=True),
    sa.Column('competitor_post_id', sa.Integer(), nullable=True),
    sa.Column('trend_item_id', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('hooks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('topics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tone', sa.String(length=100), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('content_ideas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('key_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('storyboard', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('audience_insights', sa.Text(), nullable=True),
    sa.Column('production_notes', sa.Text(), nullable=True),
    sa.Column('content_structure', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=20), nullable=True),
    sa.Column('sections_requested', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(CASE WHEN content_item_id IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN competitor_post_id IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN trend_item_id IS NOT NULL THEN 1 ELSE 0 END) = 1', name='ck_content_intelligence_one_source'),
    sa.ForeignKeyConstraint(['competitor_post_id'], ['competitor_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ci_competitor_post_id', 'content_intelligence', ['competitor_post_id'], unique=True, postgresql_where='competitor_post_id IS NOT NULL')
    op.create_index('ix_ci_content_item_id', 'content_intelligence', ['content_item_id'], unique=True, postgresql_where='content_item_id IS NOT NULL')
    op.create_index('ix_ci_status', 'content_intelligence', ['status'], unique=False)
    op.create_index('ix_ci_workspace_source', 'content_intelligence', ['workspace_id', 'source_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ci_workspace_source', table_name='content_intelligence')
    op.drop_index('ix_ci_status', table_name='content_intelligence')
    op.drop_index('ix_ci_content_item_id', table_name='content_intelligence', postgresql_where='content_item_id IS NOT NULL')
    op.drop_index('ix_ci_competitor_post_id', table_name='content_intelligence', postgresql_where='competitor_post_id IS NOT NULL')
    op.drop_table('content_intelligence')
    # ### end Alembic commands ###
