"""add FK and unique index for trend_item_id in content_intelligence

Revision ID: 8ae1731bf9f0
Revises: ee855b0184e8
Create Date: 2026-03-19 13:50:06.671766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8ae1731bf9f0'
down_revision: Union[str, None] = 'ee855b0184e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_analyses_content_item_id'), table_name='content_analyses')
    op.drop_index(op.f('ix_content_analyses_status'), table_name='content_analyses')
    op.drop_table('content_analyses')
    op.drop_table('competitor_post_analyses')
    op.create_index('ix_ci_trend_item_id', 'content_intelligence', ['trend_item_id'], unique=True, postgresql_where='trend_item_id IS NOT NULL')
    op.create_foreign_key(None, 'content_intelligence', 'trend_items', ['trend_item_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'content_intelligence', type_='foreignkey')
    op.drop_index('ix_ci_trend_item_id', table_name='content_intelligence', postgresql_where='trend_item_id IS NOT NULL')
    op.create_table('competitor_post_analyses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('transcript', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('transcript_language', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hooks', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('key_points', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('topics', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('tone', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('content_structure', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('content_ideas', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('quality_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['competitor_posts.id'], name=op.f('competitor_post_analyses_post_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('competitor_post_analyses_pkey')),
    sa.UniqueConstraint('post_id', name=op.f('competitor_post_analyses_post_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('content_analyses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content_item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('theses', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('hooks', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('storyboard', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('celery_task_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('content_ideas', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('audience_insights', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('production_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], name=op.f('content_analyses_content_item_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('content_analyses_pkey'))
    )
    op.create_index(op.f('ix_content_analyses_status'), 'content_analyses', ['status'], unique=False)
    op.create_index(op.f('ix_content_analyses_content_item_id'), 'content_analyses', ['content_item_id'], unique=True)
    # ### end Alembic commands ###
