"""add competitor intelligence tables

Revision ID: 8e5a0f3d541a
Revises: a8b9c0d1e2f3
Create Date: 2026-03-18 10:21:22.829213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e5a0f3d541a'
down_revision: Union[str, None] = 'a8b9c0d1e2f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitor_channels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('added_by_user_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('platform_id', sa.String(length=255), nullable=False),
    sa.Column('handle', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=500), nullable=True),
    sa.Column('avatar_url', sa.String(length=2048), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('subscribers_count', sa.Integer(), nullable=True),
    sa.Column('posts_count', sa.Integer(), nullable=True),
    sa.Column('avg_views', sa.Float(), nullable=True),
    sa.Column('avg_er', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('parse_frequency_hours', sa.Integer(), nullable=False),
    sa.Column('last_parsed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('parse_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['added_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_competitor_channels_last_parsed', 'competitor_channels', ['last_parsed_at'], unique=False)
    op.create_index('ix_competitor_channels_status', 'competitor_channels', ['status'], unique=False)
    op.create_index('ix_competitor_channels_workspace', 'competitor_channels', ['workspace_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_competitor_channels_ws_platform_pid', 'competitor_channels', ['workspace_id', 'platform', 'platform_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('competitor_channel_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('subscribers_count', sa.Integer(), nullable=True),
    sa.Column('posts_count', sa.Integer(), nullable=True),
    sa.Column('avg_views_30d', sa.Float(), nullable=True),
    sa.Column('avg_er_30d', sa.Float(), nullable=True),
    sa.Column('total_views_30d', sa.Integer(), nullable=True),
    sa.Column('posts_count_30d', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['competitor_channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_competitor_snapshots_channel_recorded', 'competitor_channel_snapshots', ['channel_id', 'recorded_at'], unique=False)
    op.create_table('competitor_posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('platform_post_id', sa.String(length=255), nullable=False),
    sa.Column('post_url', sa.String(length=2048), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=2048), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=30), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('views_count', sa.Integer(), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.Column('shares_count', sa.Integer(), nullable=True),
    sa.Column('er_score', sa.Float(), nullable=True),
    sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('analysis_status', sa.String(length=30), nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('analysis_error', sa.Text(), nullable=True),
    sa.Column('sent_to_library', sa.Boolean(), nullable=False),
    sa.Column('library_item_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['competitor_channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['library_item_id'], ['library_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_competitor_posts_analysis_status', 'competitor_posts', ['analysis_status'], unique=False)
    op.create_index('ix_competitor_posts_channel', 'competitor_posts', ['channel_id'], unique=False)
    op.create_index('ix_competitor_posts_channel_post', 'competitor_posts', ['channel_id', 'platform_post_id'], unique=True)
    op.create_index('ix_competitor_posts_channel_published', 'competitor_posts', ['channel_id', 'published_at'], unique=False)
    op.create_index('ix_competitor_posts_published', 'competitor_posts', ['published_at'], unique=False)
    op.create_table('competitor_notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('notification_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['competitor_channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['competitor_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_competitor_notifications_unread', 'competitor_notifications', ['workspace_id', 'is_read'], unique=False, postgresql_where=sa.text('is_read = FALSE'))
    op.create_index('ix_competitor_notifications_workspace', 'competitor_notifications', ['workspace_id'], unique=False)
    op.create_table('competitor_post_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('transcript_language', sa.String(length=10), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('hooks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('key_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('topics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tone', sa.String(length=100), nullable=True),
    sa.Column('content_structure', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_ideas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['competitor_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('competitor_post_analyses')
    op.drop_index('ix_competitor_notifications_workspace', table_name='competitor_notifications')
    op.drop_index('ix_competitor_notifications_unread', table_name='competitor_notifications', postgresql_where=sa.text('is_read = FALSE'))
    op.drop_table('competitor_notifications')
    op.drop_index('ix_competitor_posts_published', table_name='competitor_posts')
    op.drop_index('ix_competitor_posts_channel_published', table_name='competitor_posts')
    op.drop_index('ix_competitor_posts_channel_post', table_name='competitor_posts')
    op.drop_index('ix_competitor_posts_channel', table_name='competitor_posts')
    op.drop_index('ix_competitor_posts_analysis_status', table_name='competitor_posts')
    op.drop_table('competitor_posts')
    op.drop_index('ix_competitor_snapshots_channel_recorded', table_name='competitor_channel_snapshots')
    op.drop_table('competitor_channel_snapshots')
    op.drop_index('ix_competitor_channels_ws_platform_pid', table_name='competitor_channels', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_competitor_channels_workspace', table_name='competitor_channels', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_competitor_channels_status', table_name='competitor_channels')
    op.drop_index('ix_competitor_channels_last_parsed', table_name='competitor_channels')
    op.drop_table('competitor_channels')
    # ### end Alembic commands ###
