"""add_library_extended_node_fields

Revision ID: 956b5a89bbdd
Revises: 07cd7a2eda2b
Create Date: 2026-03-16 12:15:23.486757

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "956b5a89bbdd"
down_revision: str | None = "07cd7a2eda2b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("library_items", sa.Column("speaker_node_id", sa.Integer(), nullable=True))
    op.add_column("library_items", sa.Column("content_goal_node_id", sa.Integer(), nullable=True))
    op.add_column("library_items", sa.Column("narrative_node_id", sa.Integer(), nullable=True))
    op.add_column("library_items", sa.Column("hook_type_node_id", sa.Integer(), nullable=True))
    op.add_column("library_items", sa.Column("product_node_id", sa.Integer(), nullable=True))
    op.add_column("library_items", sa.Column("tone_node_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "library_items_product_node_id_fkey",
        "library_items",
        "knowledge_nodes",
        ["product_node_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "library_items_hook_type_node_id_fkey",
        "library_items",
        "knowledge_nodes",
        ["hook_type_node_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "library_items_narrative_node_id_fkey",
        "library_items",
        "knowledge_nodes",
        ["narrative_node_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "library_items_tone_node_id_fkey",
        "library_items",
        "knowledge_nodes",
        ["tone_node_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "library_items_speaker_node_id_fkey",
        "library_items",
        "knowledge_nodes",
        ["speaker_node_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "library_items_content_goal_node_id_fkey",
        "library_items",
        "knowledge_nodes",
        ["content_goal_node_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("library_items_content_goal_node_id_fkey", "library_items", type_="foreignkey")
    op.drop_constraint("library_items_speaker_node_id_fkey", "library_items", type_="foreignkey")
    op.drop_constraint("library_items_tone_node_id_fkey", "library_items", type_="foreignkey")
    op.drop_constraint("library_items_narrative_node_id_fkey", "library_items", type_="foreignkey")
    op.drop_constraint("library_items_hook_type_node_id_fkey", "library_items", type_="foreignkey")
    op.drop_constraint("library_items_product_node_id_fkey", "library_items", type_="foreignkey")
    op.drop_column("library_items", "tone_node_id")
    op.drop_column("library_items", "product_node_id")
    op.drop_column("library_items", "hook_type_node_id")
    op.drop_column("library_items", "narrative_node_id")
    op.drop_column("library_items", "content_goal_node_id")
    op.drop_column("library_items", "speaker_node_id")
    # ### end Alembic commands ###
