"""add_knowledge_graph_and_company_members

Revision ID: a449b211dd87
Revises: 8f4620605110
Create Date: 2026-03-13 13:37:13.744804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a449b211dd87'
down_revision: Union[str, None] = '8f4620605110'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'company_id', name='uq_company_member_user_company')
    )
    op.create_index('ix_company_members_company_id', 'company_members', ['company_id'], unique=False)
    op.create_index('ix_company_members_user_id', 'company_members', ['user_id'], unique=False)
    op.create_table('knowledge_nodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('node_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('scope_type', sa.String(length=20), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=False),
    sa.Column('position_x', sa.Float(), nullable=False),
    sa.Column('position_y', sa.Float(), nullable=False),
    sa.Column('is_position_fixed', sa.Boolean(), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(company_id IS NOT NULL AND workspace_id IS NULL) OR (company_id IS NULL AND workspace_id IS NOT NULL)', name='ck_knowledge_nodes_scope'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_kn_company', 'knowledge_nodes', ['company_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_kn_type_company', 'knowledge_nodes', ['node_type', 'company_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_kn_type_workspace', 'knowledge_nodes', ['node_type', 'workspace_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_kn_workspace', 'knowledge_nodes', ['workspace_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('knowledge_edges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_node_id', sa.Integer(), nullable=False),
    sa.Column('target_node_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_node_id'], ['knowledge_nodes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['target_node_id'], ['knowledge_nodes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ke_source', 'knowledge_edges', ['source_node_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_ke_target', 'knowledge_edges', ['target_node_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('uq_ke_pair_label', 'knowledge_edges', ['source_node_id', 'target_node_id', 'label'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('knowledge_node_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('node_type', sa.String(length=30), nullable=False),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('change_type', sa.String(length=20), nullable=False),
    sa.Column('change_summary', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['knowledge_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_knv_node_version', 'knowledge_node_versions', ['node_id', sa.literal_column('version_number DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_knv_node_version', table_name='knowledge_node_versions')
    op.drop_table('knowledge_node_versions')
    op.drop_index('uq_ke_pair_label', table_name='knowledge_edges', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_ke_target', table_name='knowledge_edges', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_ke_source', table_name='knowledge_edges', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('knowledge_edges')
    op.drop_index('ix_kn_workspace', table_name='knowledge_nodes', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_kn_type_workspace', table_name='knowledge_nodes', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_kn_type_company', table_name='knowledge_nodes', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_kn_company', table_name='knowledge_nodes', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('knowledge_nodes')
    op.drop_index('ix_company_members_user_id', table_name='company_members')
    op.drop_index('ix_company_members_company_id', table_name='company_members')
    op.drop_table('company_members')
    # ### end Alembic commands ###
