"""add notes to content_plan_items

Revision ID: a82ad052df80
Revises: e33d870558be
Create Date: 2026-03-16 18:40:41.788580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a82ad052df80'
down_revision: Union[str, None] = 'e33d870558be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_plan_items', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_plan_items', 'notes')
    # ### end Alembic commands ###
