"""add language region keyword_mode to trend_niches

Revision ID: c69d816d613d
Revises: 0427f58ba939
Create Date: 2026-03-19 17:28:00.296964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c69d816d613d'
down_revision: Union[str, None] = '0427f58ba939'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trend_niches', sa.Column('language', sa.String(length=10), server_default='ru', nullable=True))
    op.add_column('trend_niches', sa.Column('region', sa.String(length=10), server_default='RU', nullable=True))
    op.add_column('trend_niches', sa.Column('keyword_mode', sa.String(length=20), server_default='separate', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trend_niches', 'keyword_mode')
    op.drop_column('trend_niches', 'region')
    op.drop_column('trend_niches', 'language')
    # ### end Alembic commands ###
