"""add processing_step to content_items

Revision ID: c7de8c3861e3
Revises: 8bbd4d787381
Create Date: 2026-03-12 12:31:01.660760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7de8c3861e3'
down_revision: Union[str, None] = '8bbd4d787381'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_items', sa.Column('processing_step', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_items', 'processing_step')
    # ### end Alembic commands ###
