"""add_staff_org_id_and_platform_role

Revision ID: cae9c6b78bd8
Revises: 7bb6fdcdad61
Create Date: 2026-03-20 08:06:10.115796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cae9c6b78bd8'
down_revision: Union[str, None] = '7bb6fdcdad61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('staff_org_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'companies', ['staff_org_id'])
    op.add_column('users', sa.Column('platform_role', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'platform_role')
    op.drop_constraint(None, 'companies', type_='unique')
    op.drop_column('companies', 'staff_org_id')
    # ### end Alembic commands ###
