"""remove_tiktok_from_platform_enum

Revision ID: d29c354bb0b1
Revises: 8e5a0f3d541a
Create Date: 2026-03-18 14:48:10.616117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd29c354bb0b1'
down_revision: Union[str, None] = '8e5a0f3d541a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kgc_company'), table_name='kg_conflicts')
    op.drop_index(op.f('ix_kgc_workspace'), table_name='kg_conflicts')
    op.create_index('ix_kgc_company_node', 'kg_conflicts', ['company_node_id'], unique=False)
    op.create_index('ix_kgc_workspace_node', 'kg_conflicts', ['workspace_node_id'], unique=False)
    op.drop_index(op.f('ix_kg_public_links_is_active'), table_name='kg_public_links')
    op.drop_index(op.f('ix_kg_public_links_scope'), table_name='kg_public_links')
    op.drop_constraint(op.f('kg_public_links_created_by_user_id_fkey'), 'kg_public_links', type_='foreignkey')
    op.create_foreign_key(None, 'kg_public_links', 'users', ['created_by_user_id'], ['id'])
    op.drop_index(op.f('ix_knowledge_edges_edge_type_def_id'), table_name='knowledge_edges')
    op.drop_index(op.f('ix_kn_review'), table_name='knowledge_nodes', postgresql_where="((deleted_at IS NULL) AND ((status)::text = 'active'::text))")
    op.drop_index(op.f('ix_kn_status'), table_name='knowledge_nodes', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('ix_knowledge_nodes_node_type_def_id'), table_name='knowledge_nodes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_knowledge_nodes_node_type_def_id'), 'knowledge_nodes', ['node_type_def_id'], unique=False)
    op.create_index(op.f('ix_kn_status'), 'knowledge_nodes', ['status'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('ix_kn_review'), 'knowledge_nodes', ['last_reviewed'], unique=False, postgresql_where="((deleted_at IS NULL) AND ((status)::text = 'active'::text))")
    op.create_index(op.f('ix_knowledge_edges_edge_type_def_id'), 'knowledge_edges', ['edge_type_def_id'], unique=False)
    op.drop_constraint(None, 'kg_public_links', type_='foreignkey')
    op.create_foreign_key(op.f('kg_public_links_created_by_user_id_fkey'), 'kg_public_links', 'users', ['created_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_kg_public_links_scope'), 'kg_public_links', ['scope_type', 'scope_id'], unique=False)
    op.create_index(op.f('ix_kg_public_links_is_active'), 'kg_public_links', ['is_active'], unique=False)
    op.drop_index('ix_kgc_workspace_node', table_name='kg_conflicts')
    op.drop_index('ix_kgc_company_node', table_name='kg_conflicts')
    op.create_index(op.f('ix_kgc_workspace'), 'kg_conflicts', ['workspace_node_id'], unique=False)
    op.create_index(op.f('ix_kgc_company'), 'kg_conflicts', ['company_node_id'], unique=False)
    # ### end Alembic commands ###
