"""add_orientation_to_trend_items

Revision ID: e96df782c808
Revises: c69d816d613d
Create Date: 2026-03-19 17:55:09.064725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e96df782c808'
down_revision: Union[str, None] = 'c69d816d613d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trend_items', sa.Column('orientation', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trend_items', 'orientation')
    # ### end Alembic commands ###
