"""add trend discovery tables

Revision ID: ee855b0184e8
Revises: c3d4e5f6a7b8
Create Date: 2026-03-19 11:02:18.527583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee855b0184e8'
down_revision: Union[str, None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trend_niches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('platforms', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('monitoring_interval_hours', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trend_niches_is_active', 'trend_niches', ['is_active'], unique=False)
    op.create_index('ix_trend_niches_workspace', 'trend_niches', ['workspace_id'], unique=False)
    op.create_table('trend_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('niche_id', sa.Integer(), nullable=True),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('platform_post_id', sa.String(length=255), nullable=False),
    sa.Column('post_url', sa.String(length=2048), nullable=True),
    sa.Column('title', sa.String(length=1000), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=2048), nullable=True),
    sa.Column('channel_name', sa.String(length=500), nullable=True),
    sa.Column('channel_url', sa.String(length=2048), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('views_count', sa.BigInteger(), nullable=False),
    sa.Column('likes_count', sa.Integer(), nullable=False),
    sa.Column('comments_count', sa.Integer(), nullable=False),
    sa.Column('shares_count', sa.Integer(), nullable=False),
    sa.Column('er_score', sa.Float(), nullable=True),
    sa.Column('velocity', sa.Float(), nullable=True),
    sa.Column('acceleration', sa.Float(), nullable=True),
    sa.Column('viral_score', sa.Float(), nullable=True),
    sa.Column('stage', sa.String(length=20), nullable=True),
    sa.Column('competitor_post_id', sa.Integer(), nullable=True),
    sa.Column('analysis_status', sa.String(length=30), nullable=False),
    sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competitor_post_id'], ['competitor_posts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['niche_id'], ['trend_niches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trend_items_analysis_status', 'trend_items', ['analysis_status'], unique=False)
    op.create_index('ix_trend_items_detected_at', 'trend_items', ['detected_at'], unique=False)
    op.create_index('ix_trend_items_niche', 'trend_items', ['niche_id'], unique=False)
    op.create_index('ix_trend_items_stage', 'trend_items', ['stage'], unique=False)
    op.create_index('ix_trend_items_viral_score', 'trend_items', ['viral_score'], unique=False)
    op.create_index('ix_trend_items_ws_platform_post', 'trend_items', ['workspace_id', 'platform', 'platform_post_id'], unique=True)
    op.create_table('trend_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('niche_id', sa.Integer(), nullable=True),
    sa.Column('trend_item_id', sa.Integer(), nullable=True),
    sa.Column('alert_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('threshold_triggered', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['niche_id'], ['trend_niches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trend_item_id'], ['trend_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trend_alerts_created', 'trend_alerts', ['created_at'], unique=False)
    op.create_index('ix_trend_alerts_unread', 'trend_alerts', ['workspace_id', 'is_read'], unique=False, postgresql_where=sa.text('is_read = FALSE'))
    op.create_table('trend_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trend_item_id', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('views_count', sa.BigInteger(), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.Column('velocity', sa.Float(), nullable=True),
    sa.Column('viral_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['trend_item_id'], ['trend_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trend_snapshots_item_recorded', 'trend_snapshots', ['trend_item_id', 'recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trend_snapshots_item_recorded', table_name='trend_snapshots')
    op.drop_table('trend_snapshots')
    op.drop_index('ix_trend_alerts_unread', table_name='trend_alerts', postgresql_where=sa.text('is_read = FALSE'))
    op.drop_index('ix_trend_alerts_created', table_name='trend_alerts')
    op.drop_table('trend_alerts')
    op.drop_index('ix_trend_items_ws_platform_post', table_name='trend_items')
    op.drop_index('ix_trend_items_viral_score', table_name='trend_items')
    op.drop_index('ix_trend_items_stage', table_name='trend_items')
    op.drop_index('ix_trend_items_niche', table_name='trend_items')
    op.drop_index('ix_trend_items_detected_at', table_name='trend_items')
    op.drop_index('ix_trend_items_analysis_status', table_name='trend_items')
    op.drop_table('trend_items')
    op.drop_index('ix_trend_niches_workspace', table_name='trend_niches')
    op.drop_index('ix_trend_niches_is_active', table_name='trend_niches')
    op.drop_table('trend_niches')
    # ### end Alembic commands ###
